
[workspace]
resolver = "2"
members = ["wapo", "wapod", "wapo-host", "wapo-macro", "wapo-env"]

[patch.crates-io]
hyper-util = { git = "https://github.com/kvinwang/hyper-util", branch = "connection-tokioio" }
