
[workspace]
resolver = "2"
members = [
    "wapo",
    "wapod",
    "wapo-host",
    "wapo-macro",
    "wapo-env",
    "wapod-rpc",
    "wapo-run",
    "wapod-crypto",
    "wapod-crypto-types",
    "e2e/guest",
]

[profile.release]
panic = "abort"
