[package]
edition = "2021"
name = "httpclient-demo"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
once_cell = "1.10.0"
hyper = { version = "0.14.18", features = ["http1", "client"] }

[dependencies.wapo]
version = "0.1.0"
path = "../../wapo"
features = ["hyper-v0"]
