[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.16"
once_cell = "1.10.0"
hyper = { version = "0.14.18", features = ["http1", "client"] }
sha2 = "0.10.8"

[dependencies.wapo]
version = "0.1.0"
path = "../../wapo"
features = ["hyper-v0"]
