[package]
name = "e2e-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
wapo = { path = "../../wapo" }
log = "0.4"
anyhow = "1.0.83"
tokio = { version = "1", features = ["macros", "io-util"] }
parse-size = { version = "1.0.0", features = ["std"] }
