[package]
edition = "2021"
name = "httpserver-demo"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
anyhow = "1.0.86"
wapo = { version = "0.1", path = "../../wapo", features = ["hyper-v1"]}
hyper = { version = "1", features = ["server", "http1"] }
