[default]
workers = 8
max_blocking = 64
ident = "Wapod"
temp_dir = "/tmp"
keep_alive = 10
log_level = "normal"

[default.limits]
bytes = "8KiB"
data-form = "2MiB"
file = "1MiB"
form = "32KiB"
json = "1MiB"
msgpack = "1MiB"
string = "8KiB"

[admin]
address = "127.0.0.1"
port = 8001

[user]
address = "0.0.0.0"
port = 8002
